on: [push, pull_request]

jobs:
  java:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - run: mvn --version
      - run: mvn install --errors --batch-mode
      - run: mvn test --errors --batch-mode
        working-directory: test
